theme: jekyll-theme-architect
markdown: kramdown

title: Savannah CRM
description: Documentation for Savannah CRM
google_analytics: UA-21725789-6

url: "http://docs.savannahhq.com"
plugins:
  - jekyll-sitemap
parse_block_html: true